kind: pipeline
type: kubernetes
name: coffee-re-frame
metadata:
  namespace: drone
trigger:
  branch:
  - master

steps:
- name: build
  image: clojure:lein
  commands:
  - apt-get update
  - apt-get install -y --no-install-recommends make
  - curl -sL https://deb.nodesource.com/setup_14.x | bash
  - apt-get install -y nodejs
  - node -v
  - npm -v
  - lein deps
  - lein release

- name: upload_image
  image: plugins/docker
  when:
    event:
      exclude:
      - pull_request
  settings:
    mtu: 1000
    registry: rg.fr-par.scw.cloud/dockerregistry
    username: nologin
    password:
      from_secret: registry_password
    repo: rg.fr-par.scw.cloud/dockerregistry/coffee-re-frame
    tags: ${DRONE_BUILD_NUMBER}
    dockerfile: Dockerfile
